version: '3.7'

services:
  # --------------------------------------- WEB SITES ------------------------------------------------------------------
  incubateur_data_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: incubateur_data_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 20s
    ports:
      - "80:80"
    networks:
      - ingress
    external_links:
      - incubateur_data_mysql:incubateur_data_mysql

networks:
  ingress:
    external: false

