version: '3.7'

services:
  # --------------------------------------- DATABASES ------------------------------------------------------------------
  incubateur_data_mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 20s
    environment:
      - MYSQL_DATABASE=sii
      - MYSQL_ROOT_PASSWORD=root1234
    networks:
      - ingress
#    env_file:
#      - ../stack.env
    volumes:
      - incubateur_data_mysql_data:/var/lib/mysql

volumes:
  incubateur_data_mysql_data:

networks:
  ingress:
    external: false

  # --------------------------------------- WEB SITES ------------------------------------------------------------------

  incubateur_data_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: incubateur_data_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 20s
    ports:
      - "80:80"
    networks:
      - ingress
    external_links:
      - incubateur_data_mysql:incubateur_data_mysql

networks:
  ingress:
    external: false
 #----------------------------------------------------------------------------------------------------------------------
