name: Check Docker Compose
on:
  push:
    branches:
      - main
jobs:
  docker_test:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Start Docker Compose DB
      run: docker compose -f docker-compose-db.yml up -d
    - name: Build and Start Docker Compose WEB
      run: docker compose -f docker-compose-web.yml up -d  
    - name: Check Container Status
      run: docker compose ps
