name: Check Container

on: [push]

jobs:
  check_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t my-image .
    - name: Run Docker Container
      run: docker run --name my-container -d my-image
    - name: Check Container Status
      run: docker ps | grep my-container
